name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Verificação da sintaxe do script 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Verifica a sintaxe do script
        run: bash -n status-check.sh

  test:
    name: Simulação da execução de testes  
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Simula a execução de testes
        run: |
          echo "Running tests"
          exit 0

  package:
    name: Geração de artefato e realização do upload  
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Cria o artefato ZIP
        run: |
          mkdir -p report
          echo "Relatório de teste" > report/report.txt
          cp status-check.sh report/
          zip -r report.zip report

      - name: Faz o upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip
