name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Simular deploy 
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      PROD_DOMAIN: ${{ vars.PROD_DOMAIN }}
    steps:
      - name: Simula deploy
        run: echo "Deploying to $PROD_DOMAIN"
